spring:
  application:
    name: fund-api-project
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: busanbank
    password: abc1234!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true

kofia:
  api:
    base-url: https://apis.data.go.kr/1160100/service/GetKofiaStatisticsInfoService
    service-key: 8b78454bd4af1cfb488f9dbf25e18c07f68bb37fa063579c0a6726d35eb1afce